# Generated by Django 5.2.8 on 2025-11-30 09:36

from django.db import migrations


def create_initial_tests(apps, schema_editor):
    """Create initial test types."""
    Test = apps.get_model('core', 'Test')
    Test.objects.get_or_create(name='X-ray')
    Test.objects.get_or_create(name='Ultrasound')
    Test.objects.get_or_create(name='Blood Test')


def reverse_create_initial_tests(apps, schema_editor):
    """Reverse migration - remove initial test types."""
    Test = apps.get_model('core', 'Test')
    Test.objects.filter(name__in=['X-ray', 'Ultrasound', 'Blood Test']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_tests, reverse_create_initial_tests),
    ]
