# Generated by Django 5.2.8 on 2025-11-29 09:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Patient Name')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('contact_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message="Contact number must be 10 digits starting with '07'.", regex='^07\\d{8}$')], verbose_name='Contact Number')),
            ],
        ),
        migrations.CreateModel(
            name='TestCatalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100, unique=True, verbose_name='Test Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(verbose_name='Date')),
                ('booking_time', models.TimeField(verbose_name='Time Slot')),
                ('hospital_name', models.CharField(max_length=100, verbose_name='Hospital Name')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_app.patient')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking_app.testcatalogue')),
            ],
            options={
                'verbose_name_plural': 'Bookings',
                'unique_together': {('patient', 'test', 'booking_date', 'booking_time')},
            },
        ),
    ]
